### ISSUE TITLE
unable to import fastify autoload

### ISSUE THREAD

**Issue by harshsharma22** [fastify/fastify-autoload#120]
## 🐛 Bug Report

unable to run fastify server when importing fastify-autoload

## To Reproduce

npm install --save fastify-autoload
const autoload = require('fastify-autoload')
```js
const fastify = require('fastify')
const path = require('path')
const autoload = require('fastify-autoload')
const app= fastify({ logger: true })


  const startFastify = async () => {
    try {
      await app.listen(3333);
      app.log.info(`server listening on ${app.server.address().port}`);
    } catch (err) {
      app.log.error(err);
      process.exit(1);
    }
  };
  
  startFastify();
```

## Expected behavior

server should start
```js
// Paste the expected results here
```

## Your Environment

- *node version*: 8.10.0
- *fastify version*: >=3.8.0
- *os*:  Linux
- *any other relevant information*

**Comment by mcollina** [comment]
What error are you getting? Are you using Node 8?

**Comment by harshsharma22** [comment]
> What error are you getting? Are you using Node 8?

Yes i am using node 8
getting this error
```/home/harsh/node_modules/fastify-autoload/index.js:120
    content = await import(url.pathToFileURL(file).href)
                    ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)```

**Comment by jsumners** [comment]
Node 8 does not support ESM syntax.

**Comment by mcollina** [comment]
This module supports 10+
