### ISSUE TITLE
UnhandledPromiseRejectionWarning when a folder is loaded without entrypoint

### ISSUE THREAD

**Issue by PatrickHeneise** [fastify/fastify-autoload#34]
```js
fastify.register(AutoLoad, {
  dir: path.join(__dirname, 'foo')
})
```

if "foo" contains .js files but not index.js nor package.json to define an entry point, the following error is thrown:

```
(node:4277) UnhandledPromiseRejectionWarning: Error: Cannot find module '/api/services/orders'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at steed.map (/api/node_modules/fastify-autoload/index.js:77:26)
    at ResultsHolder.release (/api/node_modules/fastparallel/parallel.js:185:9)
    at SingleCaller.release (/api/node_modules/fastparallel/parallel.js:157:17)
    at fs.readdir (/api/node_modules/fastify-autoload/index.js:47:13)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

#33 addresses this issue by loading .js files within a folder.

**Comment by mcollina** [comment]
Fixed in #33
