### ISSUE TITLE
potential issues in combination with avvio? crashing when using fastify v5

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify-autoload#386]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

@mcollina 
@climba03003 
@jsumners 

run `node --trace-warnings ./test/commonjs/basic.js`

```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/fastify-autoload$ node --trace-warnings ./test/commonjs/basic.js
TAP version 13
1..107
(node:34513) [FSTWRN002] FastifyWarning: The /home/aras/workspace/fastify-autoload/test/commonjs/basic/index/index.js plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
    at FastifyWarning (/home/aras/workspace/fastify-autoload/node_modules/process-warning/index.js:78:17)
    at Object.checkPluginHealthiness (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:141:5)
    at Object.registerPlugin (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:147:26)
    at Boot.override (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(node:34513) [FSTWRN002] FastifyWarning: The /home/aras/workspace/fastify-autoload/test/commonjs/basic/index/bar/index.js plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
    at FastifyWarning (/home/aras/workspace/fastify-autoload/node_modules/process-warning/index.js:78:17)
    at Object.checkPluginHealthiness (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:141:5)
    at Object.registerPlugin (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:147:26)
    at Boot.override (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(node:34513) [FSTWRN002] FastifyWarning: The /home/aras/workspace/fastify-autoload/test/commonjs/basic/routeParams/index.js plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
    at FastifyWarning (/home/aras/workspace/fastify-autoload/node_modules/process-warning/index.js:78:17)
    at Object.checkPluginHealthiness (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:141:5)
    at Object.registerPlugin (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:147:26)
    at Boot.override (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(node:34513) [FSTWRN002] FastifyWarning: The /home/aras/workspace/fastify-autoload/test/commonjs/basic/routeParams/foo/index.js plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
    at FastifyWarning (/home/aras/workspace/fastify-autoload/node_modules/process-warning/index.js:78:17)
    at Object.checkPluginHealthiness (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:141:5)
    at Object.registerPlugin (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:147:26)
    at Boot.override (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(node:34513) [FSTWRN002] FastifyWarning: The /home/aras/workspace/fastify-autoload/test/commonjs/basic/routeParams/foo/_id1/index.js plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
    at FastifyWarning (/home/aras/workspace/fastify-autoload/node_modules/process-warning/index.js:78:17)
    at Object.checkPluginHealthiness (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:141:5)
    at Object.registerPlugin (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:147:26)
    at Boot.override (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(node:34513) [FSTWRN002] FastifyWarning: The /home/aras/workspace/fastify-autoload/test/commonjs/basic/routeParams/foo/_id1/bar/_id2/index.js plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
    at FastifyWarning (/home/aras/workspace/fastify-autoload/node_modules/process-warning/index.js:78:17)
    at Object.checkPluginHealthiness (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:141:5)
    at Object.registerPlugin (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:147:26)
    at Boot.override (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(node:34513) [FSTWRN002] FastifyWarning: The /home/aras/workspace/fastify-autoload/test/commonjs/basic/encapsulate/plugin2.js plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
    at FastifyWarning (/home/aras/workspace/fastify-autoload/node_modules/process-warning/index.js:78:17)
    at Object.checkPluginHealthiness (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:141:5)
    at Object.registerPlugin (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginUtils.js:147:26)
    at Boot.override (/home/aras/workspace/fastify-autoload/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/home/aras/workspace/fastify-autoload/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
ok 1 - should not error
ok 2 - should be equal
ok 3 - should not error
ok 4 - should be equal
ok 5 - should be equivalent
```

**Comment by climba03003** [comment]
It is fixed in `next` branch.

**Comment by jsumners** [comment]
What is the question for me? I really don't pay attention to this module.

**Comment by Uzlopak** [comment]
@climba03003 
good to know

@jsumners 
We already get warnings regarding potential error throwing. And I wanted to make it aware, that we could run into issues.

If Kaka writes it is already fixed, then I can close it ;).

**Comment by climba03003** [comment]
It is fixed in part of `v5` updates.
https://github.com/fastify/fastify-autoload/pull/379
