### ISSUE TITLE
Validation Errors Not Attached in plugins From autoloaded routes

### ISSUE THREAD

**Issue by esatterwhite** [fastify/fastify-autoload#81]
## 🐛 Bug Report

I'm using this plugin to load plugins from 2 different directories. Plugins and routes. One of the plugins calls `setErrorHandler`. the routes set `attachValidation: true`, but the error handler is never passed back an validation information

I can tell that is is a validation error based on the message, but the actual validation errors are never attached 

```
    Error: account is required!
        at Object.$main (eval at build (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fast-json-stringify/index.js:149:20), <anonymous>:133:15)
        at serialize (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/validation.js:132:41)
        at preserializeHookEnd (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/reply.js:306:15)
        at preserializeHook (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/reply.js:293:5)
        at _Reply.Reply.send (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/reply.js:146:7)
        at /home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/wrapThenable.js:27:15
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## To Reproduce

```
├── plugins
│   ├── health-check.js
│   ├── http-404.js
│   ├── http-error.js
│   ├── load-fastify-schema.js
│   ├── route-map.js
│   └── swagger.js
├── README.md
├── routes
│   └── v1
│       └── account
│           └── post-account.js
├── index.js
```

### Server
```javascript
const path = require('path')
const fastify = require('fastify')
const Autoload = require('fastify-autoload')
const server = fastify({logger: log})

server.register(AutoLoad, {
  dir: path.join(__dirname, 'plugins')
})

server.register(AutoLoad, {
  dir: path.join(__dirname, 'routes', 'v1')
, options: {prefix: 'v1/'}
})

module.exports = server

if (require.main === module) {
  process.once('SIGTERM', onSignal)
  process.once('SIGINT', onSignal)

  startup()
    .catch(/* istanbul ignore next */(err) => {
      server.log.error(err, 'server failed to start')
      process.nextTick(() => {
        throw err
      })
    })
}

async function startup() {
  await server.ready()
  await server.listen(3000)
  server.log.debug(server.printRoutes())
}
async function onSignal(signal) {
  server.log.info(`system signal received ${signal}`)
  try {
    await server.close()
  } catch (err) {
    /* istanbul ignore next */
    server.log.error(err, {err})
  }
}
```

### Route

```javascript
const fluent = require('fluent-schema')

module.exports = {
  path: '/'
, method: 'POST'
, attachValidation: true
, schema: {
    body: fluent
      .object()
      .prop('status', fluent.string().enum(['trial'])).valueOf()
  }
, handler: async (req, res) => {
    return {foo: 'bar'}
  }
}
```
### Error Plugin

```javascript
'use strict'

const {STATUS_CODES} = require('http')
const plugin = require('fastify-plugin')

const EINTERNAL = 'EINTERNAL'

module.exports = plugin(httpError, {
  name: '@answerbook/fastify-http-error'
, fastify: '>=2.0.0'
})

function httpError(fastify, opts, next) {
  fastify.setErrorHandler((err, req, res) => {
    consol.log('validation', req.validationError)
    const log = req.log
    const {statusCode = 500} = err
    const fn = statusCode >= 500
      ? log.error.bind(log)
      : log.warn.bind(log)

    fn(err)
    res
      .code(statusCode)
      .type('application/json')
      .send({
        message: STATUS_CODES[statusCode]
      , code: err.code || EINTERNAL
      , status: statusCode
      })

  })
  fastify.log.debug('[plugin]: http-error loaded')
  next()
}
```
## Expected behavior
Validation errors should be attached to the error or request 

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Linux

**Comment by esatterwhite** [comment]
If I just add the route manually, it works ok.

**Comment by mcollina** [comment]
```
    Error: account is required!
        at Object.$main (eval at build (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fast-json-stringify/index.js:149:20), <anonymous>:133:15)
        at serialize (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/validation.js:132:41)
        at preserializeHookEnd (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/reply.js:306:15)
        at preserializeHook (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/reply.js:293:5)
        at _Reply.Reply.send (/home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/reply.js:146:7)
        at /home/esatterwhite/dev/logdna/accounts-service/node_modules/fastify/lib/wrapThenable.js:27:15
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Is emitted during serialization, not validation. I would count this as a programming error and not something you should handle in code.

Note that in your example there is no "account" mentioned at all.

**Comment by esatterwhite** [comment]
This is the schema i'm using
```javascript
module.exports = schema
  .object()
  .id('account')
  .title('Account')
  .description('Represents a single LogDNA customer account')
  .prop('account', schema.string().required())
  .prop('billing', schema.object())
  .prop('cluster', schema.object())
  .prop('company', schema.string().required())
  .prop('deactivated', schema.string().format(FORMATS.DATE_TIME))
  .prop('es', schema.object())
  .prop('exclusions', schema.array().items(schema.object()))
  .prop('externalid', schema.string())
  .prop('features', schema.object()) // fixme
  .prop('integrations', schema.object())
  .prop('key', schema.array().items(schema.string()).required())
  .prop('lastdata', schema.string().format(FORMATS.DATE_TIME))
  .prop('lastlogin', schema.string().format(FORMATS.DATE_TIME))
  .prop('meta', schema.object())
  .prop('owneremail', schema.string().format(FORMATS.EMAIL).required())
  .prop('ownerip', schema.string())
  .prop('partner', schema.object())
  .prop('plan', schema.ref('account-service#/definitions/plan'))
  .prop('quota', schema.object())
  .prop('referrrer', schema.string())
  .prop('servicekeys', schema.array().items(schema.string()))
  .prop('stats', schema.object())
  .prop('status', schema.string().enum(['active', 'deactivated']).required())
  .prop('sandbox', schema.object())
```

**Comment by esatterwhite** [comment]
> Is emitted during serialization, not validation. I would count this as a programming error and not something you should handle in code.

Ok, What am I doing wrong?

**Comment by esatterwhite** [comment]
If I take exactly the same route and manually call `fastify.route` on it in the main server file it does exactly what I would expect. If its loaded with the autoloader, it does not. I'm at a bit of a loss as to what I need to fix / change.

**Comment by esatterwhite** [comment]
I can step through the code, and it gets [here](https://github.com/fastify/fastify/blob/master/lib/validation.js#L82-L85)

I can see the error getting created, but something wierd happens and it returns false.

**Comment by mcollina** [comment]
> Ok, What am I doing wrong?

I don't know. I cannot see your code and your example does not reproduce the problem. My bet is that you are using the same schema in 2 places.

Note that from the stack trace you pasted, the error is thrown by fast-json-strringify after the preSerialization hook (see https://www.fastify.io/docs/latest/Lifecycle/).

**Comment by esatterwhite** [comment]
here is an example https://github.com/esatterwhite/fastify-example

```
LOGLEVEL=debug LOGPRETTY=1 node index.js
curl -XPOST http://localhost:3000/v1/account -H 'Content-Type: application/json' -d '{"x": 1}'
```

**Comment by esatterwhite** [comment]
@mcollina does this help? If the `attachValidation` flag is set to true, I'm able to post anything to the route and it will pass validation. If you remove it, It will at least result in an error.

**Comment by mcollina** [comment]
I think the code is working as expected.

With `attachValidation: true`, the route handler is called even if validation fails with `req.validationError` set. With `attachValidation: false`, the route handler is not called and the error handler is called instead with the validation error as the first parameter. `req.validationError` is not set.

**Comment by esatterwhite** [comment]
Oh. I see. I was just looking in the wrong place! Thanks.
